name: gpt-research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - beautifulsoup4=4.12.3
  - colorama=0.4.6
  - python-dotenv=1.0.1
  - pyyaml=6.0.2
  - uvicorn
  - pydantic=2.9.2
  - fastapi
  - jinja2=3.1.4
  - aiofiles=24.1.0
  - mistune=3.0.2
  - loguru=0.7.2
  - weasyprint
  - pip:
    - websockets==13.1
    - python-multipart==0.0.10
    - markdown==3.7
    - md2pdf==1.0.1
    - tiktoken==0.7.0
    - htmldocx==0.0.6
    - lxml_html_clean==0.2.2
    - unstructured==0.15.13
    - json_repair==0.29.3
    - json5==0.9.25
    - langchain==0.2.16
    - langchain_community==0.2.17
    - langchain-openai==0.1.25
    - langchain-core==0.2.41
    - langgraph
    - langgraph-cli
    - gpt-researcher==0.9.6
    - arxiv==2.1.3
    - PyMuPDF==1.24.10
    - openai==1.47.0
    - aiohappyeyeballs==2.4.0
    - aiohttp==3.10.5
    - httpx==0.27.2
    - nltk==3.9.1
    - pillow==10.4.0
    - langchain_anthropic
    - langchain_cohere
    - langchain_google_vertexai
    - langchain_google_genai
    - langchain_fireworks
    - langchain_together
    - langchain_mistralai
    - langchain_huggingface
    - langchain_groq
    - langchain_aws
    - duckduckgo-search
    - selenium
    - browser_cookie3