name: gpt-research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - beautifulsoup4
  - colorama
  - python-dotenv
  - pyyaml
  - uvicorn
  - pydantic
  - fastapi
  - jinja2
  - aiofiles
  - mistune
  - loguru
  - requests
  - nltk
  - pip:
    - md2pdf
    - python-multipart
    - markdown
    - langchain
    - langchain_community
    - langchain-openai
    - langchain-ollama
    - langgraph
    - langgraph-cli
    - tiktoken
    - gpt-researcher
    - arxiv
    - PyMuPDF
    - python-docx
    - htmldocx
    - lxml_html_clean
    - websockets
    - unstructured
    - json_repair
    - json5
    - openai
    - langchain_anthropic
    - langchain_cohere
    - langchain_google_vertexai
    - langchain_google_genai
    - langchain_fireworks
    - langchain_together
    - langchain_mistralai
    - langchain_huggingface
    - langchain_groq
    - langchain_aws
    - duckduckgo-search
    - selenium
    - browser_cookie3
    - aiohappyeyeballs==2.4.0